"""empty message

Revision ID: 745f820c759a
Revises: d6d9bd83f60b
Create Date: 2024-03-07 11:29:06.330913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745f820c759a'
down_revision = 'd6d9bd83f60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('subscription_id')

    # ### end Alembic commands ###
