name: Lint Workflow

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Lint Action
      uses: wearerequired/lint-action@v2.3.0
